import { GoogleTask, GoogleTaskList } from '../types/task';

export const INITIAL_MOCK_LISTS: GoogleTaskList[] = [
  { id: 'list-work', title: '工作项目 💼' },
  { id: 'list-personal', title: '生活成长 🌱' },
  { id: 'list-learning', title: '技术探索 🚀' },
];

export const INITIAL_MOCK_TASKS: Record<string, GoogleTask[]> = {
  'list-work': [
    {
      id: 'task-1',
      title: '开发 Google Tasks 增强版看板 #dev #feature',
      notes: '构建纯前端无后端单页应用，支持多状态分栏与实时同步。 #urgent',
      status: 'needsAction',
      updated: new Date().toISOString(),
      position: '00000000000000000001',
    },
    {
      id: 'task-1-1',
      title: '设计看板拖拽交互 #doing',
      parent: 'task-1',
      notes: '基于 @hello-pangea/dnd 支持平滑拖动与状态流转',
      status: 'needsAction',
      updated: new Date().toISOString(),
      position: '00000000000000000002',
    },
    {
      id: 'task-1-2',
      title: '实现子母任务折叠与进度统计条',
      parent: 'task-1',
      notes: '基于 Google Tasks parent 字段计算 2/4 完成度',
      status: 'completed',
      completed: new Date().toISOString(),
      updated: new Date().toISOString(),
      position: '00000000000000000003',
    },
    {
      id: 'task-1-3',
      title: '构建 #标签 胶囊徽章与顶栏快速筛选',
      parent: 'task-1',
      notes: '支持中英文标签匹配与颜色哈希',
      status: 'completed',
      completed: new Date().toISOString(),
      updated: new Date().toISOString(),
      position: '00000000000000000004',
    },
    {
      id: 'task-1-4',
      title: '配置 GitHub Actions 自动发布到 GitHub Pages',
      parent: 'task-1',
      status: 'needsAction',
      updated: new Date().toISOString(),
      position: '00000000000000000005',
    },
    {
      id: 'task-2',
      title: '重构前端工程化构建流程 #dev',
      notes: '升级 Vite 8 与现代 TypeScript 配置，消除构建警告',
      status: 'needsAction',
      updated: new Date().toISOString(),
      position: '00000000000000000006',
    },
    {
      id: 'task-3',
      title: '完成 Q3 季度产品设计评审 #doing #review',
      notes: '输出交互原型并与团队对齐关键链路',
      status: 'needsAction',
      updated: new Date().toISOString(),
      position: '00000000000000000007',
    },
    {
      id: 'task-4',
      title: '完成 Google Cloud OAuth 2.0 凭据申请',
      notes: '在 GCP 控制台已创建 Web 应用凭据，获取 Client ID',
      status: 'completed',
      completed: new Date().toISOString(),
      updated: new Date().toISOString(),
      position: '00000000000000000008',
    },
  ],
  'list-personal': [
    {
      id: 'task-p1',
      title: '每周运动计划 🏃 #health #life',
      notes: '保持良好的身体状态',
      status: 'needsAction',
      updated: new Date().toISOString(),
      position: '00000000000000000001',
    },
    {
      id: 'task-p1-1',
      title: '周二慢跑 5 公里',
      parent: 'task-p1',
      status: 'completed',
      completed: new Date().toISOString(),
      updated: new Date().toISOString(),
      position: '00000000000000000002',
    },
    {
      id: 'task-p1-2',
      title: '周四核心力量训练 #doing',
      parent: 'task-p1',
      status: 'needsAction',
      updated: new Date().toISOString(),
      position: '00000000000000000003',
    },
    {
      id: 'task-p1-3',
      title: '周末游泳放松',
      parent: 'task-p1',
      status: 'needsAction',
      updated: new Date().toISOString(),
      position: '00000000000000000004',
    },
  ],
  'list-learning': [
    {
      id: 'task-l1',
      title: '深入理解 Google Identity Services 新版标准 #learning',
      notes: '对比 Authorization Code 与 Token Client 架构区别',
      status: 'completed',
      completed: new Date().toISOString(),
      updated: new Date().toISOString(),
      position: '00000000000000000001',
    },
    {
      id: 'task-l2',
      title: '阅读 React 19 并发特性与编译器指南 #learning #react',
      notes: '学习 useActionState 与 Server Actions 原理',
      status: 'needsAction',
      updated: new Date().toISOString(),
      position: '00000000000000000002',
    },
  ],
};
